# ==================== SECURITY HOOKS ====================
- id: gitleaks
  name: GitLeaks Security Scan
  entry: gitleaks
  language: system
  args: ["detect", "--source", ".", "--verbose"]
  pass_filenames: false
  always_run: true

# ==================== ANSIBLE HOOKS ====================
- id: isort
  name: Python Import Sort
  entry: isort
  language: system
  types: [python]
  args: [--profile, black]

# ==================== DOCKER HOOKS ====================
- id: hadolint
  name: Dockerfile Lint
  entry: hadolint
  language: system
  types: [dockerfile]
  args: [--ignore, DL3008, --ignore, DL3009, --ignore, DL3015, --ignore, DL3033]

# ==================== SHELL HOOKS ====================
- id: shellcheck
  name: Shell Script Check
  entry: shellcheck
  language: system
  types: [shell]
