# Tool versions for shared pre-commit hooks
[tools]
# Core languages and runtimes
node = "20"
go = "1.21.1"
java = "corretto-11.0.25.9.1"
groovy = "2.5.1"
maven = "3.8.1"
dotnet = "8.0.403"
rust = "1.80.1"

# Infrastructure as Code
packer = "1.11.2"
opentofu = "1.8.8"
terraform = "1.9.8"
terraform-docs = "0.19.0"
terragrunt = "0.71.1"
tflint = "0.59.1"
vault = "1.18.0+ent"

# Kubernetes tools
oc = "stable-4.17"
kustomize = "5.6.0"
kubectl = "1.33.1"
k9s = "0.32.5"
k0sctl = "0.19.0"
helm = "3.16.2"
helm-ct = "3.11.0"
helm-docs = "1.14.2"
helmfile = "0.169.0"
helm-diff = "3.9.11"
kube-capacity = "0.8.0"
kube-score = "1.20.0"
kubecm = "0.33.1"
kubecolor = "0.5.2"
kubeconform = "0.7.0"
kubesec = "2.14.2"
kubeshark = "52.9.0"
kubeval = "0.16.1"
kubie = "0.26.0"

# Security scanning
gitleaks = "8.28.0"
trufflehog = "3.90.11"
committed = "1.1.7"

# Development tools
gradle = "8.10.2"
cfssl = "1.6.5"
hcl2json = "0.6.4"
neovim = "0.10.2"
pre-commit = "4.3.0"
lazygit = "0.55.1"

# Text processing and utilities
yj = "5.1.0"
yq = "4.44.3"
jq = "1.7.1"
markdownlint-cli2 = "0.18.1"
ripgrep = "15.0.0"
ripgrep-all = "0.10.9"
ripsecrets = "0.1.11"

# Docker tools
hadolint = "2.14.0"

# Python tools (will need pip install)
black = "25.9.0"

# Shell tools
shellcheck = "0.11.0"

[env]

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]
