---
default_stages: [pre-commit, manual]
default_install_hook_types: [pre-commit, pre-push, commit-msg, prepare-commit-msg]

repos:
  # Setup shared configurations (run once)
  - repo: https://github.com/ginanck/shared-pre-commit-hooks
    rev: v0.5.0
    hooks:
      - id: setup-configs

  # Security scanning
  - repo: https://github.com/ginanck/shared-pre-commit-hooks
    rev: v0.5.0
    hooks:
      - id: gitleaks

  # OpenTofu
  - repo: https://github.com/tofuutils/pre-commit-opentofu
    rev: v2.2.1
    hooks:
      - id: tofu_fmt
      - id: tofu_validate
      - id: tofu_docs
      - id: tofu_tflint
        args:
          - --args=--disable-rule=terraform_required_version
          - --args=--disable-rule=terraform_required_providers

  # General file formatting and validation
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: mixed-line-ending
        args: ["--fix=lf"]
