---
default_stages: [pre-commit, manual]
default_install_hook_types: [pre-commit, pre-push, commit-msg, prepare-commit-msg]

repos:
  # Security scanning
  - repo: https://github.com/ginanck/shared-pre-commit-hooks
    rev: master
    hooks:
      - id: gitleaks
      - id: ansible-lint
      - id: yamllint
      - id: flake8
      - id: black
      - id: isort
      - id: hadolint
      - id: shellcheck

  # General file formatting and validation
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: mixed-line-ending
        args: ["--fix=lf"]
