---
default_stages: [pre-commit, manual]
default_install_hook_types: [pre-commit, pre-push, commit-msg, prepare-commit-msg]

repos:
  # Security scanning and linting tools
  - repo: https://github.com/ginanck/shared-pre-commit-hooks
    rev: v0.13.0
    hooks:
      - id: gitleaks
      - id: isort
      - id: hadolint
      - id: shellcheck

  # Local tools (must be installed in your environment)
  - repo: local
    hooks:
      # Ansible specific tools
      - id: ansible-lint
        name: ansible-lint
        entry: ansible-lint
        language: system
        args: [-c, .config/ansible-lint.yml, -q]
        files: \.(yaml|yml)$
        exclude: ^(molecule/.*|\.github/.*|requirements\.yml$|collections/.*|roles/.*|todo/.*|ansible/.*)
      
      # YAML linting
      - id: yamllint
        name: yamllint
        entry: yamllint
        language: system
        args: [-c, .config/yamllint.yml]
        files: \.(yaml|yml)$
      
      # Python tools
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        args: [--config, .config/flake8.conf]
        files: \.py$
      
      - id: black
        name: black
        entry: black
        language: system
        args: [--config, .config/pyproject.toml]
        files: \.py$

  # General file formatting and validation
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: mixed-line-ending
        args: ["--fix=lf"]
