---
default_stages: [pre-commit, manual]
default_install_hook_types: [pre-commit, pre-push, commit-msg, prepare-commit-msg]

repos:
  # Local tools (must be installed in your environment)
  - repo: local
    hooks:
      # ==================== SECURITY HOOKS ====================
      - id: gitleaks-commit-history
        name: gitleaks-commit-history
        description: Detects and prevents secrets like passwords, API keys, and tokens from being committed to the repository
        entry: gitleaks
        language: system
        args: ["git", ".", "--verbose"]
        pass_filenames: false
        always_run: true

      - id: gitleaks-current-directory
        name: gitleaks-current-directory
        description: Detects and prevents secrets like passwords, API keys, and tokens from being committed to the repository
        entry: gitleaks
        language: system
        args: ["dir", ".", "--verbose"]
        pass_filenames: false
        always_run: true

  # OpenTofu
  - repo: https://github.com/tofuutils/pre-commit-opentofu
    rev: v2.2.1
    hooks:
      - id: tofu_fmt
        name: tofu_fmt
        description: Formats OpenTofu configuration files to ensure consistent style and readability
      - id: tofu_validate
        name: tofu_validate
        description: Validates OpenTofu configuration files for syntax errors and internal consistency
      - id: tofu_docs
        name: tofu_docs
        description: Automatically generates and updates documentation for OpenTofu modules
      - id: tofu_tflint
        name: tofu_tflint
        description: Lints OpenTofu code to find possible errors, warnings, and best practice violations
        args:
          - --args=--disable-rule=terraform_required_version
          - --args=--disable-rule=terraform_required_providers

  # General file formatting and validation
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        name: trailing-whitespace
        description: Removes trailing whitespace from the end of lines
        exclude: ^(\.pre-commit-config.*\.yaml$|\.pre-commit-hooks\.yaml$)
      - id: end-of-file-fixer
        name: end-of-file-fixer
        description: Ensures files end with a single newline character
      - id: check-added-large-files
        name: check-added-large-files
        description: Prevents accidentally committing large files (over 500KB by default)
        args: ["--maxkb=500"]
      - id: check-case-conflict
        name: check-case-conflict
        description: Checks for files that would conflict in case-insensitive filesystems
      - id: check-merge-conflict
        name: check-merge-conflict
        description: Checks for files containing merge conflict strings
      - id: check-executables-have-shebangs
        name: check-executables-have-shebangs
        description: Ensures executable files have proper shebang lines
      - id: check-shebang-scripts-are-executable
        name: check-shebang-scripts-are-executable
        description: Ensures files with shebangs are marked as executable
      - id: mixed-line-ending
        name: mixed-line-ending
        description: Replaces mixed line endings with Unix-style (LF) line endings
        args: ["--fix=lf"]
