---
# yamllint configuration for Ansible projects
extends: default

rules:
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  line-length: disable
  truthy: disable
  comments: disable
  comments-indentation: disable
  document-start: disable

ignore: |
  .cache/
  .github/
  .config/
  molecule/
  .pre-commit-config.yaml
  .pre-commit-config*.yaml
  .pre-commit-hooks.yaml
  collections/
  fact_cache/
  tmp/
  vault/
  files/helm/*.yml
  files/helm/*.yaml
  roles/
  todo/
